version: "3.9"
services:
  polebot:
    build: 
        context: .
        dockerfile: ./Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    env_file: 
        - .env